from typing import Callable, Protocol
from backend.events import AsrPartial, AsrFinal

ASREvent = AsrPartial | AsrFinal

class ASRAdapter(Protocol):
    async def connect(self) -> None: ...
    async def send_audio(self, pcm_bytes: bytes) -> None: ...
    async def flush(self) -> None: ...
    async def close(self) -> None: ...
